server:
  port: 8081

cus:
  host: http://localhost


data:
  url: jdbc:mysql://localhost:3306/shareimage
  driver: com.mysql.jdbc.Driver
  username: root
  password: 123456


sendgrid:
  api:
    key: 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

mail:
  user: projectshareimage@gmail.com
  password: a24031998

drive:
  google:
    folder:
      image-upload: 1RWUUAWJjx9X1e6JD8bkG2_XmfTdFw3HC